apiVersion: lifecycle.keptn.sh/v1
kind: KeptnAppContext
metadata:
  name: demo-app
spec:
  preDeploymentTasks:
  {{- range .Values.keptn.appContext.preDeploymentTasks }}
  - {{ . }}
  {{- end }}
  postDeploymentTasks:
  {{- range .Values.keptn.appContext.postDeploymentTasks }}
  - {{ . }}
  {{- end }}
  postDeploymentEvaluations:
  {{- range .Values.keptn.appContext.postDeploymentEvaluations }}
  - {{ . }}
  {{- end }}
  promotionTasks:
  {{- range .Values.keptn.appContext.promotionTasks }}
  - {{ . }}
  {{- end }}
  metadata:
    commitID: {{ .Values.commitID }}
