site_name: "Kyverno Keptn Workshop"
repo_url: https://github.com/heckelmann/kyverno-keptn-workshop
repo_name: heckelmann/kyverno-keptn-workshop
edit_uri: edit/main/web-docs/
docs_dir: docs

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode        
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
  font: 
    text: Exo 2
    code: Roboto Mono

nav:
  - 'Home': 'index.md'
  - 'Tutorial Steps':
      - '1: Overview': '01-workshop-introduction.md'
      - '2: Setup Lab Environment': '02-create-lab-environment.md'
      - '3: The System Explained': '03-the-system-explained.md'
      - '4: Pre Deployment Checks': '04-pre-deployment-checks.md'
      - '5: Chainsaw test': '05-chainsaw-test.md'
      - '6: Evaluate & Promote Deployments': '06-evaluate-and-promote.md'
      - '7: Deployment Observability': '07-deployment-observability.md'
  - 'Final Exam': 'final-exam.md'

# pip install mkdocs-macros-plugin
# Allows use of variables (see `extras` below)
plugins:
  - macros
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  

extra:
  # when code is updated
  # this var can be removed and
  # we can use {{ site.repo_name }} (see above)
  # instead
  temp_site_url: "heckelmann/kyverno-keptn-workshop"
  social:
    - icon: material/github
      link: https://github.com/heckelmann/kyverno-keptn-workshop
    - icon: material/twitter
      link: https://twitter.com/wurstsalat
    - icon: material/linkedin
      link: https://www.linkedin.com/in/christian-heckelmann-82375a25/
    - icon: material/linkedin
      link: https://www.linkedin.com/in/eddycharly/
