apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  namespace: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      serviceAccountName: flagd
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:latest
          args: ["start", "-p", "8013", "--sources", "[{\"uri\":\"flagd/feature-flags\",\"provider\":\"kubernetes\"}]"]
          ports:
            - containerPort: 8013
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
       
             
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
  namespace: flagd
spec:
  selector:
    app: flagd
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
  type: ClusterIP
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagd
  namespace: flagd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flagd
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - featureflagsources
  - featureflags
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flagd
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: flagd
subjects:
- kind: ServiceAccount
  name: flagd
  namespace: flagd