apiVersion: batch/v1
kind: Job
name: demo-app-load-test-{{request.object.metadata.resourceVersion}}
namespace: "demo-app-prod"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app-prod
    spec:
      containers:
      - command:
        - k6
        - run
        - https://raw.githubusercontent.com/{{ .Values.repo.name }}/{{ .Values.repo.revision }}/tasks/load-prod.js
        image: grafana/k6:0.45.0
        imagePullPolicy: IfNotPresent
        name: load-test
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 300
