apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: http-web
    nodePort: 30102
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: NodePort
