apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: jaeger
  namespace: argocd
spec:
  source:
    path: gitops/infrastructure/jaeger-operator
    repoURL: https://github.com/{{ .Values.repo.name }}
    targetRevision: {{ .Values.repo.revision }}
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true