{{ if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  podMetricsEndpoints:
  - port: http
    interval: 5s
    scrapeTimeout: 4s
{{ end }}
