apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: load-test
  namespace: demo-app-dev
spec:
  retries: 0
  timeout: "5m"
  container:
    name: k6-test
    image: grafana/k6:0.45.0
    command:
      - 'k6'
      - 'run'
      - 'https://raw.githubusercontent.com/{{ .Values.repo.name }}/{{ .Values.repo.revision }}/functions/load-dev.js'