name: chainsaw

on:
  pull_request:
    branches:
      - main

jobs:
  chainsaw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create cluster
        run: |
          kind create cluster --name workshop-cluster --config cluster/kind.yaml
      - name: install cert manager
        run: |
          helm install cert-manager --namespace cert-manager --create-namespace --wait --repo https://charts.jetstack.io cert-manager --values - <<EOF
          crds:
            enabled: true
          EOF
      - name: install keptn
        run: |
          helm install keptn --namespace keptn-system --create-namespace --wait --repo https://charts.lifecycle.keptn.sh keptn \
          --version 0.6.0 --values - <<EOF
          lifecycleOperator:
            schedulingGatesEnabled: true
            promotionTasksEnabled: true
          EOF
      - name: install kyverno
        run: |
          helm install kyverno --namespace kyverno --create-namespace --wait --repo https://kyverno.github.io/kyverno kyverno --version 3.1.4
      - name: install kyverno policies
        run: |
          kubectl apply -f gitops/infrastructure/kyverno-policies/
      - name: Install chainsaw
        uses: kyverno/action-install-chainsaw@573a9c636f7c586f86ecb9de9674176daf80ee29 # v0.2.5
